### ISSUE TITLE
Module configuration questions

### ISSUE THREAD

**Issue by Abdulrhman02** [johannschopplich/nuxt-api-party#10] opened 2023-01-25 07:01 UTC
firstly thank you guys for your amazing work and simple/clean documentation.

I don't know if my approach of spelling all my questions in one form is good or not, but I will do it so please bear with me :).

- I just notice that the header in the config file is not been passed in the call it shows an empty header I need to pass in the call for it to show in the call, this was my setup in the config for the endpoint for testing

 ```
 authAPI: {
        headers: {
          Authorization:"bearer 1234567890",
        },
        url: "http://localhost:9051/api/authenticate",
      },
```
- and second, about cache = true by default this one I think needs to be in config because it is not useful in most cases because it makes one call and needs to refresh to make another call each time 

- and the third, was about global interceptors if there is a way to make it it will be awesome to see

**Comment by johannschopplich** [comment] 2023-01-30 07:45
Generally speaking: Separate issues are better to handle. 🙂 Regarding your questions.

> I just notice that the header in the config file is not been passed in the call it shows an empty header I need to pass in the call for it to show in the call, this was my setup in the config for the endpoint for testing

Can't reproduce that. Working as expected. Maybe you've set a `token` alongside? Nuxt API Party will build the `Authorization` header if a token is set. Could you please provide a minimum reproducible example?

> and second, about cache = true by default this one I think needs to be in config because it is not useful in most cases because it makes one call and needs to refresh to make another call each time

Please create a separate issue.

> and the third, was about global interceptors if there is a way to make it it will be awesome to see

You mean apart from "local" fetch interceptors? That would be a feature request – please create an issue as well.

**Comment by johannschopplich** [comment] 2023-02-14 15:57
Closing this. @Abdulrhman02 Please create separate issues with a verbose description. Thanks in advance!

**Closed by johannschopplich** 2023-02-14 15:57 UTC
