### ISSUE TITLE
Looping requests catches only the last one

### ISSUE THREAD

**Issue by zAlweNy26** [johannschopplich/nuxt-api-party#78] opened 2024-06-27 09:12 UTC
Hi, I'm facing an issue about looping requests with this module. It works fine if I use the internal `$fetch` of Nuxt.

Here there is an example:
```ts
const requests = totalFiles.value.map((file) => {
	const formData = new FormData()
	formData.append('file', file)
	return $apiPartyFetch('my_endpoint_for_file', {
		method: 'POST',
		body: formData,
		headers: {
			Accept: 'application/json',
		}
	})
})
Promise.allSettled(requests).then((reqs) => {
	const resolved = reqs.filter(r => r.status === 'fulfilled').length
	console.log('resolved:', resolved)
}).catch((err) => {
	console.log('error', err)
})
```

_Originally posted by @zAlweNy26 in https://github.com/johannschopplich/nuxt-api-party/discussions/59#discussioncomment-9891583_

**Comment by johannschopplich** [comment] 2024-06-27 09:14
Please provide a minimum, reproducible example. Thanks!

**Comment by zAlweNy26** [comment] 2024-06-27 09:15
Yep, there it is

**Comment by johannschopplich** [comment] 2024-06-27 09:17
Thanks for the report. Can you please provide a reproducible example? Please use a template below to create a minimal reproduction:
👉 https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz
👉 https://codesandbox.io/p/github/nuxt/starter/v3-codesandbox

Thanks in advance!

**Comment by zAlweNy26** [comment] 2024-06-27 09:53
https://stackblitz.com/edit/github-cttzte?file=app.vue
I was trying to make an example but I'm unable to reproduce my problem, everything works fine on the StackBlitz environment I did. I thought it was an issue with this library because with the internal `$fetch` of Nuxt it was working just fine.
I don't know if maybe the problem is related to my backend, I'm sorry for opening an issue without a working example, I'll try other things and come back here when I'll have an example or to close the issue.

**Comment by johannschopplich** [comment] 2024-06-27 10:25
Interesting. Technically speaking, deep down Nuxt API Party uses `$fetch` as well. But with the form data serializing for the internal server proxy. 

Sure, let's leave it open for now.

**Comment by zAlweNy26** [comment] 2024-06-27 10:39
If I use the for-of loop it works... I don't understand why the `.map()` and `Promise.allSettled` combo doesn't work.

**Comment by zAlweNy26** [comment] 2024-06-27 10:49
I had to create this ugly code to make it all work....
```ts
let resolved = 0
for (const file of totalFiles.value) {
	const formData = new FormData()
	formData.append('file', file)
	try {
		await fetchMimir('rabbit_holes/file', {
			method: 'POST',
			body: formData,
		})
		resolved++
	}
	catch (resolved) {
		toast.add('error', { title: t('toasts.file.failed'), description: file.name })
	}
}
toast.add('success', { title: t('toasts.file.added', { num: resolved }, totalFiles.value.length) })
```

**Comment by zAlweNy26** [comment] 2024-06-27 10:50
If you want we can close this issue, even if I didn't fully understand where the problem is...

**Comment by johannschopplich** [comment] 2024-06-27 11:30
I don't know what the problem is either. At least we now that's not a bug of the module.
Feel free to add more info later on! I'll close the issue.

**Closed by johannschopplich** 2024-06-27 11:30 UTC
Labels: needs reproduction
